# Site settings
author: Cynthia Rittenbach
title: CER Coding 
header-img: img/home-bg.png
email: crittenbach@gmail.com
copyright_name: Cynthia Rittenbach
description: > # this means to ignore newlines until "baseurl:"
  My weekly coding updates
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Crittenbach1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
